# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: avap.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'avap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\navap.proto\x12\x04\x61vap\"\x1e\n\x0e\x43ommandRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"]\n\x0f\x43ommandResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x0c\x12\x11\n\tinterface\x18\x03 \x01(\t\x12\x0c\n\x04hash\x18\x04 \x01(\t\x12\r\n\x05\x66ound\x18\x05 \x01(\x08\x32M\n\x10\x44\x65\x66initionEngine\x12\x39\n\nGetCommand\x12\x14.avap.CommandRequest\x1a\x15.avap.CommandResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'avap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDREQUEST']._serialized_start=20
  _globals['_COMMANDREQUEST']._serialized_end=50
  _globals['_COMMANDRESPONSE']._serialized_start=52
  _globals['_COMMANDRESPONSE']._serialized_end=145
  _globals['_DEFINITIONENGINE']._serialized_start=147
  _globals['_DEFINITIONENGINE']._serialized_end=224
# @@protoc_insertion_point(module_scope)
