name: AVAP Definition Engine CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # --- JOB 1: INTEGRIDAD ---
  integrity:
    name: "STEP 1: Functional Integrity"
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: avap_user
          POSTGRES_PASSWORD: avap_password
          POSTGRES_DB: avap_db
        ports: [5432:5432]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Init DB & Test
        env:
          DATABASE_URL: postgres://avap_user:avap_password@localhost:5432/avap_db
          API_KEY: avap_secret_key_2026
        run: |
          PGPASSWORD=avap_password psql -h localhost -U avap_user -d avap_db -f init.sql
          npm test

  # --- JOB 2: CAPACIDAD ---
  capacity:
    name: "STEP 2: Raw Capacity"
    needs: integrity  # Esto crea la línea que conecta las pastillas
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run ghz Benchmark
        env:
          GHZ_DATA: '{"name":"if"}'
        run: |
          node src/server.js &
          sleep 3
          wget https://github.com/bojand/ghz/releases/download/v0.120.0/ghz-linux-x86_64.tar.gz
          tar -xf ghz-linux-x86_64.tar.gz
          ./ghz --insecure --proto ./avap.proto --call avap.DefinitionEngine.GetCommand --data "$GHZ_DATA" --metadata '{"x-avap-auth":"avap_secret_key_2026"}' --total 2000 --concurrency 10 localhost:50051

  # --- JOB 3: REGRESIÓN ---
  regression:
    name: "STEP 3: Performance Budget"
    needs: capacity # Conecta la segunda pastilla con la tercera
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          pip install grpcio grpcio-tools
          node src/server.js &
          sleep 3
          python -m grpc_tools.protoc -I. --python_out=app/core --grpc_python_out=app/core avap.proto
          sed -i 's/import avap_pb2 as avap__pb2/from . import avap_pb2 as avap__pb2/' app/core/avap_pb2_grpc.py
          python tests/benchmark_brain.py