# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import avap_pb2 as avap__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in avap_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DefinitionEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCommand = channel.unary_unary(
                '/avap.DefinitionEngine/GetCommand',
                request_serializer=avap__pb2.CommandRequest.SerializeToString,
                response_deserializer=avap__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.SyncCatalog = channel.unary_unary(
                '/avap.DefinitionEngine/SyncCatalog',
                request_serializer=avap__pb2.Empty.SerializeToString,
                response_deserializer=avap__pb2.CatalogResponse.FromString,
                _registered_method=True)


class DefinitionEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCommand(self, request, context):
        """Obtiene un solo comando (Legacy / Debug)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncCatalog(self, request, context):
        """NUEVO: Descarga el cerebro entero de una vez
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DefinitionEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCommand,
                    request_deserializer=avap__pb2.CommandRequest.FromString,
                    response_serializer=avap__pb2.CommandResponse.SerializeToString,
            ),
            'SyncCatalog': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncCatalog,
                    request_deserializer=avap__pb2.Empty.FromString,
                    response_serializer=avap__pb2.CatalogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'avap.DefinitionEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('avap.DefinitionEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DefinitionEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avap.DefinitionEngine/GetCommand',
            avap__pb2.CommandRequest.SerializeToString,
            avap__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncCatalog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/avap.DefinitionEngine/SyncCatalog',
            avap__pb2.Empty.SerializeToString,
            avap__pb2.CatalogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
