# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: avap.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'avap.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\navap.proto\x12\x04\x61vap\"\x07\n\x05\x45mpty\"\x1e\n\x0e\x43ommandRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"a\n\x0f\x43ommandResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x16\n\x0einterface_json\x18\x03 \x01(\t\x12\x0c\n\x04\x63ode\x18\x04 \x01(\t\x12\x0c\n\x04hash\x18\x05 \x01(\t\"e\n\x0f\x43\x61talogResponse\x12\'\n\x08\x63ommands\x18\x01 \x03(\x0b\x32\x15.avap.CommandResponse\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\x12\x14\n\x0cversion_hash\x18\x03 \x01(\t2\x80\x01\n\x10\x44\x65\x66initionEngine\x12\x39\n\nGetCommand\x12\x14.avap.CommandRequest\x1a\x15.avap.CommandResponse\x12\x31\n\x0bSyncCatalog\x12\x0b.avap.Empty\x1a\x15.avap.CatalogResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'avap_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_COMMANDREQUEST']._serialized_start=29
  _globals['_COMMANDREQUEST']._serialized_end=59
  _globals['_COMMANDRESPONSE']._serialized_start=61
  _globals['_COMMANDRESPONSE']._serialized_end=158
  _globals['_CATALOGRESPONSE']._serialized_start=160
  _globals['_CATALOGRESPONSE']._serialized_end=261
  _globals['_DEFINITIONENGINE']._serialized_start=264
  _globals['_DEFINITIONENGINE']._serialized_end=392
# @@protoc_insertion_point(module_scope)
